version: '3.8'

services:
  general:
    build:
      context: '.'
      dockerfile: './apps/general/Dockerfile'
      secrets:
        - npm-auth-token
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: production

secrets:
  npm-auth-token:
    environment: NODE__AUTH_TOKEN
